### ISSUE TITLE
Feature request: Support for blocking specific versions

### ISSUE THREAD

**Issue by rhnvrm** [ryancurrah/gomodguard#1]
Hey,
Wanted to ask if you think we could add support for blocking specific versions of a library.

For example, a security vulnerability has been found in a specific version (v0.1) of a project and we want to lint the go mod file for checking if the version is > v0.1, the one with the vulnerability. 

The `golang.org/x/mod/modfile` package seems to have support for parsing the version in https://godoc.org/golang.org/x/mod/modfile#Require (https://godoc.org/golang.org/x/mod/module#Version) and we seem to already be using the `.Path` (https://github.com/ryancurrah/gomodguard/blob/c1855e940177e7b5a28d286f7556250cd9c6f4a3/gomodguard.go#L325)

After going through the codebase, I had thought of two ways to go about this.

1. The easier way would be to modify the `[]string` in the allowed modules to a struct. The config would then be something like:

```yml
allowed:
  modules:                                                      
    - [github.com/go-xmlfmt/xmlfmt, v0.1]
```

But this is going to break compatibility with previous versions, and is also confusing/ugly.

2. Write a parser to parse the string into a struct

This way we can retain compatibility and would be easier as well. 

```yml
allowed:
  modules:                                                      
    - github.com/go-xmlfmt/xmlfmt
    - github.com/go-xmlfmt/xmlfmt@v0.1
    - github.com/go-xmlfmt/xmlfmt>v0.1
```

Here all three are acceptable keys. 

If you think this would be good to add, I would be happy to contribute to writing this feature.

**Comment by ryancurrah** [comment]
Hey @rhnvrm thanks for your interest in the project! This is something I felt that eventually come up.

A few things from me:

1. I would like to add some tests before having external contributors. So I should do that this week.
2. Semver lib should be used https://github.com/Masterminds/semver. It includes goodies like parsing versions.
3. Without changing the formatting of allowed modules we could expand on blocked modules with something like below:

```
allowed:
  modules:
    - github.com/go-xmlfmt/xmlfmt

blocked:
  modules: 
    - github.com/go-xmlfmt/xmlfmt:
        version: < 0.1
        reason: "Versions less than 0.1 are missing a critical feature."  # Reason why the version is blocked
```
