### ISSUE TITLE
Don't match modules by prefix

### ISSUE THREAD

**Issue by austinbyers** [ryancurrah/gomodguard#30]
I'd like to block `github.com/aws/aws-sdk-go` in favor of `github.com/aws/aws-sdk-go-v2` (via `golangci-lint`):

```yml
linters-settings:
  depguard:
    list-type: denylist
    packages:
      # This works, but I'd rather use gomodguard
      - github.com/aws/aws-sdk-go/**  # Use github.com/aws/aws-sdk-go-v2 instead

  gomodguard:
    blocked:
      modules:
        - github.com/aws/aws-sdk-go:
            recommendations:
              - github.com/aws/aws-sdk-go-v2
```

Since modules are matched by prefix: https://github.com/ryancurrah/gomodguard/blob/349d1ba8b47d3b0d37bec7406118220e1e9e87a7/gomodguard.go#L446

This will always fail:

```
utilities/encryption.go:9:2: import of package `github.com/aws/aws-sdk-go-v2/service/kms` is blocked because the module is in the blocked modules list. `github.com/aws/aws-sdk-go-v2` is a recommended module. (gomodguard)
	"github.com/aws/aws-sdk-go-v2/service/kms"
	^
```

---

I realize switching to an equality match would be a breaking change, but maybe supporting the glob format as `depguard` does would help alleviate that? Or adding an option to disable prefix matching?
