### ISSUE TITLE
support deny deps by regex

### ISSUE THREAD

**Issue by leaxoy** [ryancurrah/gomodguard#47]
In some scenarios, a large number of dependencies with similar names will be used within the organization, and this tool can be used to reject these dependencies according to regular rules.

Example:
```
xxx.org/yyy/aaa
xxx.org/yyy/bbb
xxx.org/yyy/ccc
```
for config:
```yaml
blocked:
  regexps:
    xxx.org/yyy/\w+:
      reason: should use xxx.org/yyy/common instead
```
